### PR TITLE
15 fix wall walking

### LINKED ISSUE #15: Fix Wall Walking
Currently, you are able to walk along the walls just by running against them. It also halts upwards momentum. Not sure _why_ this happens, but it's a problem. Especially when platforms you need to jump on are involved.

### PR DESCRIPTION
**Pull request by kjy5**
Fixes #15 (maybe)?
- Solve being unable to jump and move at the same time
- Makes the walls and the platforms "slippery" so you don't get stuck on them. we may need to tune the values of things though

### CODE REVIEW

**Review by kaeberc — COMMENTED** [review]
It's really slippery, and extremely hard to move blocks around where you want them. Why did you increase the mass from 10 to 50?

**Comment by kjy5** [comment]
I'm using forces to move about now so the mass plays a factor. Maybe the boxes also need to have their mass scale? Using forces is the correct way to move, but the solution for being stuck on walls is to be slippery

**Comment by julialwang** [comment]
Just got around to this -- I think I have to agree with Connor that the permeation to the push objects is a bit crazy. Especially in such a small enclosed space -- is there some friction we should look into for the interact-able objects? Jumping & lack of wall-climbing looks great btw.

**Comment by kjy5** [comment]
Maybe we can try to add a friction material to them? This could motivate a grabbing (#17) mechanic. I'm super busy right now, but I will try to do this. Maybe by this weekend

**Pull request merged**
